[package]
name = "ciao"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = { version = "0.10.0", default-features = false, features = ["spin_mutex"] }

[features]
default = []
std = []
